description: >
    This defines DHCP client configuration.
properties:
    - name: ClientIdentifier
      type: enum[self.ClientIdentifier]
      description: >
          This is passed as client ID in the DHCP request.
      default: MACAddress
    - name: DUIDType
      type: enum[self.DUIDType]
      description: >
          This specifies how the DUID should be generated.
      default: LinkLayer
      errors:
        - xyz.openbmc_project.Common.Error.NotSupported
    - name: DNSEnabled
      type: boolean
      description: >
          if true then the DNS servers received from the DHCP server
          will be used and take precedence over any statically configured ones.
    - name: NTPEnabled
      type: boolean
      description: >
          if true then the NTP servers received from the DHCP server
          will be used by systemd-timesyncd and take precedence over any
          statically configured ones.
    - name: HostNameEnabled
      type: boolean
      description: >
          if true then the hostname received from the DHCP server
          will be set as the transient hostname of the system.
    - name: DomainEnabled
      type: boolean
      description: >
          if true then the domain names received from the DHCP server
          will be used by systemd-resolved and take precedence over any
          statically configured ones.
    - name: SendHostNameEnabled
      type: boolean
      description: >
          if true then DHCP option 12 is enabled i.e machine`s hostname will be
          sent to the DHCP server.

enumerations:
    - name: ClientIdentifier
      description: >
          Possible Client Identifiers.
      values:
        - name: MACAddress
          description: >
              Generate client ID based on MAC address.
        - name: DUID
          description: >
              Generate RFC-4361 based client ID.
        - name: DUIDOnly
          description: >
              Generate RFC non-compliant client ID.

    - name: DUIDType
      description: >
          Possible DUID types.
      values:
        - name: Vendor
          description: >
              DUID will be generated using machine-id.
        - name: UUID
          description: >
              Product UUID is used as DUID.
        - name: LinkLayerTime
          description: >
              MAC address of the interface and an additional time value
              after a colon is used as DUID value. 
        - name: LinkLayer
          description: >
              MAC address of the interface is used as DUID value.



